# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(389, 142)
        About.setMinimumSize(QtCore.QSize(389, 142))
        About.setMaximumSize(QtCore.QSize(389, 142))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VBC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        About.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(40, 40, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("VBC.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(About)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 201, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(About)
        self.label_3.setGeometry(QtCore.QRect(130, 60, 131, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(About)
        self.label_4.setGeometry(QtCore.QRect(240, 60, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(About)
        self.label_5.setGeometry(QtCore.QRect(120, 90, 231, 21))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "关于本软件"))
        self.label_2.setText(_translate("About", "VBC 车桥耦合振动分析程序 作者信息"))
        self.label_3.setText(_translate("About", "计算内核：李奇"))
        self.label_4.setText(_translate("About", "界面交互：吴阅"))
        self.label_5.setText(_translate("About", "同济大学 桥梁工程系 轨道交通桥梁研究室"))
