# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ErrorReminder.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrorReminder(object):
    def setupUi(self, ErrorReminder):
        ErrorReminder.setObjectName("ErrorReminder")
        ErrorReminder.resize(665, 475)
        self.errorText = QtWidgets.QPlainTextEdit(ErrorReminder)
        self.errorText.setGeometry(QtCore.QRect(30, 50, 611, 401))
        self.errorText.setObjectName("errorText")
        self.errorReminder = QtWidgets.QLabel(ErrorReminder)
        self.errorReminder.setGeometry(QtCore.QRect(40, 20, 581, 16))
        self.errorReminder.setAccessibleName("")
        self.errorReminder.setObjectName("errorReminder")

        self.retranslateUi(ErrorReminder)
        QtCore.QMetaObject.connectSlotsByName(ErrorReminder)

    def retranslateUi(self, ErrorReminder):
        _translate = QtCore.QCoreApplication.translate
        ErrorReminder.setWindowTitle(_translate("ErrorReminder", "Form"))
        self.errorReminder.setText(_translate("ErrorReminder", "输入存在以下错误，操作已终止："))
