# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExtForceTimeHistDef.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExtForceTimeHistDef(object):
    def setupUi(self, ExtForceTimeHistDef):
        ExtForceTimeHistDef.setObjectName("ExtForceTimeHistDef")
        ExtForceTimeHistDef.resize(1251, 712)
        ExtForceTimeHistDef.setMinimumSize(QtCore.QSize(1251, 712))
        ExtForceTimeHistDef.setMaximumSize(QtCore.QSize(1251, 712))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VBC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ExtForceTimeHistDef.setWindowIcon(icon)
        self.extForceTimeHistTable = QtWidgets.QTableWidget(ExtForceTimeHistDef)
        self.extForceTimeHistTable.setGeometry(QtCore.QRect(30, 60, 331, 581))
        self.extForceTimeHistTable.setObjectName("extForceTimeHistTable")
        self.extForceTimeHistTable.setColumnCount(3)
        self.extForceTimeHistTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.extForceTimeHistTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.extForceTimeHistTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.extForceTimeHistTable.setHorizontalHeaderItem(2, item)
        self.extForceTimeHistTable.verticalHeader().setVisible(False)
        self.extForcePlot = MatplotlibWidget(ExtForceTimeHistDef)
        self.extForcePlot.setGeometry(QtCore.QRect(380, 10, 841, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extForcePlot.sizePolicy().hasHeightForWidth())
        self.extForcePlot.setSizePolicy(sizePolicy)
        self.extForcePlot.setObjectName("extForcePlot")
        self.extForceTimeHistAdd = QtWidgets.QPushButton(ExtForceTimeHistDef)
        self.extForceTimeHistAdd.setGeometry(QtCore.QRect(30, 30, 51, 23))
        self.extForceTimeHistAdd.setObjectName("extForceTimeHistAdd")
        self.extForceTimeHistDel = QtWidgets.QPushButton(ExtForceTimeHistDef)
        self.extForceTimeHistDel.setGeometry(QtCore.QRect(90, 30, 51, 23))
        self.extForceTimeHistDel.setObjectName("extForceTimeHistDel")
        self.refreshPlot = QtWidgets.QPushButton(ExtForceTimeHistDef)
        self.refreshPlot.setGeometry(QtCore.QRect(280, 30, 71, 23))
        self.refreshPlot.setObjectName("refreshPlot")
        self.layoutWidget = QtWidgets.QWidget(ExtForceTimeHistDef)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 670, 1231, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.extForceSave = QtWidgets.QPushButton(self.layoutWidget)
        self.extForceSave.setObjectName("extForceSave")
        self.horizontalLayout.addWidget(self.extForceSave)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.extForceAbandon = QtWidgets.QPushButton(self.layoutWidget)
        self.extForceAbandon.setObjectName("extForceAbandon")
        self.horizontalLayout.addWidget(self.extForceAbandon)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)

        self.retranslateUi(ExtForceTimeHistDef)
        QtCore.QMetaObject.connectSlotsByName(ExtForceTimeHistDef)

    def retranslateUi(self, ExtForceTimeHistDef):
        _translate = QtCore.QCoreApplication.translate
        ExtForceTimeHistDef.setWindowTitle(_translate("ExtForceTimeHistDef", "Dialog"))
        item = self.extForceTimeHistTable.horizontalHeaderItem(0)
        item.setText(_translate("ExtForceTimeHistDef", "序号"))
        item = self.extForceTimeHistTable.horizontalHeaderItem(1)
        item.setText(_translate("ExtForceTimeHistDef", "时刻(s)"))
        item = self.extForceTimeHistTable.horizontalHeaderItem(2)
        item.setText(_translate("ExtForceTimeHistDef", "外力(矩)(N(·m))"))
        self.extForceTimeHistAdd.setText(_translate("ExtForceTimeHistDef", "+"))
        self.extForceTimeHistDel.setText(_translate("ExtForceTimeHistDef", "-"))
        self.refreshPlot.setText(_translate("ExtForceTimeHistDef", "更新图像"))
        self.extForceSave.setText(_translate("ExtForceTimeHistDef", "保存"))
        self.extForceAbandon.setText(_translate("ExtForceTimeHistDef", "放弃"))
from MatplotlibWidget import MatplotlibWidget
