# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PostTableShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PostTableShow(object):
    def setupUi(self, PostTableShow):
        PostTableShow.setObjectName("PostTableShow")
        PostTableShow.resize(1097, 681)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VBC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PostTableShow.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(PostTableShow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.browser = QtWebEngineWidgets.QWebEngineView(PostTableShow)
        self.browser.setObjectName("browser")
        self.verticalLayout_2.addWidget(self.browser)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(PostTableShow)
        QtCore.QMetaObject.connectSlotsByName(PostTableShow)

    def retranslateUi(self, PostTableShow):
        _translate = QtCore.QCoreApplication.translate
        PostTableShow.setWindowTitle(_translate("PostTableShow", "计算结果汇总表"))
from PyQt5 import QtWebEngineWidgets
