# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeHistPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeHistPlot(object):
    def setupUi(self, TimeHistPlot):
        TimeHistPlot.setObjectName("TimeHistPlot")
        TimeHistPlot.resize(1344, 518)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TimeHistPlot.sizePolicy().hasHeightForWidth())
        TimeHistPlot.setSizePolicy(sizePolicy)
        TimeHistPlot.setMinimumSize(QtCore.QSize(1344, 518))
        TimeHistPlot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VBC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TimeHistPlot.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TimeHistPlot)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeHistPlot = MatplotlibWidget(TimeHistPlot)
        self.timeHistPlot.setObjectName("timeHistPlot")
        self.horizontalLayout.addWidget(self.timeHistPlot)
        self.fftPlot = MatplotlibWidget(TimeHistPlot)
        self.fftPlot.setObjectName("fftPlot")
        self.horizontalLayout.addWidget(self.fftPlot)

        self.retranslateUi(TimeHistPlot)
        QtCore.QMetaObject.connectSlotsByName(TimeHistPlot)

    def retranslateUi(self, TimeHistPlot):
        _translate = QtCore.QCoreApplication.translate
        TimeHistPlot.setWindowTitle(_translate("TimeHistPlot", "后处理时程图"))
from MatplotlibWidget import MatplotlibWidget
