# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindForceVehAssign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windForceVehAssign(object):
    def setupUi(self, windForceVehAssign):
        windForceVehAssign.setObjectName("windForceVehAssign")
        windForceVehAssign.resize(941, 547)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(windForceVehAssign.sizePolicy().hasHeightForWidth())
        windForceVehAssign.setSizePolicy(sizePolicy)
        windForceVehAssign.setMinimumSize(QtCore.QSize(941, 547))
        windForceVehAssign.setMaximumSize(QtCore.QSize(941, 547))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VBC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        windForceVehAssign.setWindowIcon(icon)
        self.windForceVehAssignTable = QtWidgets.QTableWidget(windForceVehAssign)
        self.windForceVehAssignTable.setGeometry(QtCore.QRect(20, 20, 901, 471))
        self.windForceVehAssignTable.setObjectName("windForceVehAssignTable")
        self.windForceVehAssignTable.setColumnCount(5)
        self.windForceVehAssignTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.windForceVehAssignTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.windForceVehAssignTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.windForceVehAssignTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.windForceVehAssignTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.windForceVehAssignTable.setHorizontalHeaderItem(4, item)
        self.windForceVehAssignTable.verticalHeader().setVisible(False)
        self.windForceVehAssignSave = QtWidgets.QPushButton(windForceVehAssign)
        self.windForceVehAssignSave.setGeometry(QtCore.QRect(290, 510, 75, 23))
        self.windForceVehAssignSave.setObjectName("windForceVehAssignSave")
        self.windForceVehAssignAbandon = QtWidgets.QPushButton(windForceVehAssign)
        self.windForceVehAssignAbandon.setGeometry(QtCore.QRect(560, 510, 75, 23))
        self.windForceVehAssignAbandon.setObjectName("windForceVehAssignAbandon")

        self.retranslateUi(windForceVehAssign)
        QtCore.QMetaObject.connectSlotsByName(windForceVehAssign)

    def retranslateUi(self, windForceVehAssign):
        _translate = QtCore.QCoreApplication.translate
        windForceVehAssign.setWindowTitle(_translate("windForceVehAssign", "车辆风荷载分配"))
        item = self.windForceVehAssignTable.horizontalHeaderItem(0)
        item.setText(_translate("windForceVehAssign", "车辆序号"))
        item = self.windForceVehAssignTable.horizontalHeaderItem(1)
        item.setText(_translate("windForceVehAssign", "车辆名"))
        item = self.windForceVehAssignTable.horizontalHeaderItem(2)
        item.setText(_translate("windForceVehAssign", "是否均匀风场"))
        item = self.windForceVehAssignTable.horizontalHeaderItem(3)
        item.setText(_translate("windForceVehAssign", "控制点1处风荷载"))
        item = self.windForceVehAssignTable.horizontalHeaderItem(4)
        item.setText(_translate("windForceVehAssign", "控制点2处风荷载"))
        self.windForceVehAssignSave.setText(_translate("windForceVehAssign", "保存"))
        self.windForceVehAssignAbandon.setText(_translate("windForceVehAssign", "放弃"))
