# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindFieldCtrlPtDef.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windFieldCtrlPtDef(object):
    def setupUi(self, windFieldCtrlPtDef):
        windFieldCtrlPtDef.setObjectName("windFieldCtrlPtDef")
        windFieldCtrlPtDef.resize(341, 567)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(windFieldCtrlPtDef.sizePolicy().hasHeightForWidth())
        windFieldCtrlPtDef.setSizePolicy(sizePolicy)
        windFieldCtrlPtDef.setMinimumSize(QtCore.QSize(341, 567))
        windFieldCtrlPtDef.setMaximumSize(QtCore.QSize(341, 567))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("VBC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        windFieldCtrlPtDef.setWindowIcon(icon)
        self.windFieldCtrlPointOrderDown = QtWidgets.QPushButton(windFieldCtrlPtDef)
        self.windFieldCtrlPointOrderDown.setGeometry(QtCore.QRect(280, 20, 31, 23))
        self.windFieldCtrlPointOrderDown.setObjectName("windFieldCtrlPointOrderDown")
        self.windFieldCtrlPointAdd = QtWidgets.QPushButton(windFieldCtrlPtDef)
        self.windFieldCtrlPointAdd.setGeometry(QtCore.QRect(160, 20, 31, 23))
        self.windFieldCtrlPointAdd.setObjectName("windFieldCtrlPointAdd")
        self.label_8 = QtWidgets.QLabel(windFieldCtrlPtDef)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 121, 21))
        self.label_8.setObjectName("label_8")
        self.windFieldCtrlPointDel = QtWidgets.QPushButton(windFieldCtrlPtDef)
        self.windFieldCtrlPointDel.setGeometry(QtCore.QRect(200, 20, 31, 23))
        self.windFieldCtrlPointDel.setObjectName("windFieldCtrlPointDel")
        self.windFieldCtrlPointTable = QtWidgets.QTableWidget(windFieldCtrlPtDef)
        self.windFieldCtrlPointTable.setGeometry(QtCore.QRect(20, 50, 301, 461))
        self.windFieldCtrlPointTable.setObjectName("windFieldCtrlPointTable")
        self.windFieldCtrlPointTable.setColumnCount(2)
        self.windFieldCtrlPointTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.windFieldCtrlPointTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.windFieldCtrlPointTable.setHorizontalHeaderItem(1, item)
        self.windFieldCtrlPointTable.horizontalHeader().setDefaultSectionSize(138)
        self.windFieldCtrlPointTable.verticalHeader().setVisible(False)
        self.windFieldCtrlPointOrderUp = QtWidgets.QPushButton(windFieldCtrlPtDef)
        self.windFieldCtrlPointOrderUp.setGeometry(QtCore.QRect(240, 20, 31, 23))
        self.windFieldCtrlPointOrderUp.setObjectName("windFieldCtrlPointOrderUp")
        self.windFieldCtrlPointSave = QtWidgets.QPushButton(windFieldCtrlPtDef)
        self.windFieldCtrlPointSave.setGeometry(QtCore.QRect(80, 530, 71, 23))
        self.windFieldCtrlPointSave.setObjectName("windFieldCtrlPointSave")
        self.windFieldCtrlPointAbandon = QtWidgets.QPushButton(windFieldCtrlPtDef)
        self.windFieldCtrlPointAbandon.setGeometry(QtCore.QRect(190, 530, 71, 23))
        self.windFieldCtrlPointAbandon.setObjectName("windFieldCtrlPointAbandon")

        self.retranslateUi(windFieldCtrlPtDef)
        QtCore.QMetaObject.connectSlotsByName(windFieldCtrlPtDef)

    def retranslateUi(self, windFieldCtrlPtDef):
        _translate = QtCore.QCoreApplication.translate
        windFieldCtrlPtDef.setWindowTitle(_translate("windFieldCtrlPtDef", "车道沿线非均匀风场控制点编辑"))
        self.windFieldCtrlPointOrderDown.setText(_translate("windFieldCtrlPtDef", "↓"))
        self.windFieldCtrlPointAdd.setText(_translate("windFieldCtrlPtDef", "+"))
        self.label_8.setText(_translate("windFieldCtrlPtDef", "车道沿线风场控制点"))
        self.windFieldCtrlPointDel.setText(_translate("windFieldCtrlPtDef", "-"))
        item = self.windFieldCtrlPointTable.horizontalHeaderItem(0)
        item.setText(_translate("windFieldCtrlPtDef", "序号"))
        item = self.windFieldCtrlPointTable.horizontalHeaderItem(1)
        item.setText(_translate("windFieldCtrlPtDef", "X(m)"))
        self.windFieldCtrlPointOrderUp.setText(_translate("windFieldCtrlPtDef", "↑"))
        self.windFieldCtrlPointSave.setText(_translate("windFieldCtrlPtDef", "保存"))
        self.windFieldCtrlPointAbandon.setText(_translate("windFieldCtrlPtDef", "放弃"))
